# docker file is simple text file with instructions to build a docker image

## we need a base image with Node.js [we have webapp so we can use node image]
FROM node


# Create a working directory inside the container
WORKDIR /app

# COPY entire current [project] to /app
COPY . /app

# Install dependencies
RUN npm install

# Expose the port the app runs on
EXPOSE 8000
CMD ["npm", "run","dev"]



# Now build the docker image using below command
# Commands:
    # go to directory where this dockerfile is located
    # docker build . [dot means current directory]


# now image is created than list all images using below command
# docker image ls


# now run the image using below command [below command will run the app inside the container not on our local machine]
# docker run <image_id>


# Port 1 :which i want to run the app
# Port 2 : which is exposed in dockerfile using EXPOSE keyword

# now run the image in our local machine using below command
# docker run -p <port 1>:<port 2> <image_id>


# now run the image on detached mode using below command [this helps that even if we close the terminal the app will run in background]
# docker run -d -p <port 1>:<port 2> <image_id>


# Image naming [how to give name or tag to our image]
# -t [is for tag]
# docker build -t <image_name>:<tag> .



# How to see all the running containers
# docker ps [list all the running containers]
# docker ps -a [list all the containers including stopped ones]

# How to stop a running container
# docker stop <container_id> / docker stop <container_name>:<tag>

# How to delete the image [note first delete all the containers which are running using that image]
# docker rmi <image_id>  / docker rmi <image_name>:<tag>


# docker image
# 1. docker build -t <image_name>:<tag> .

# Docker container
# 1. docker run  -d —rm -p  <binded port><exposed port we did in docker file> <container id>
# 2. -rm [means it will remove automatically when we stop the container]
# 3. docker run -d —rm —name “customer name of container” -p <binded port><exposed port we did in docker file> <image id>
# 4. add —name [to give a custom name to docker container



# Push docker image to docker hub
# 1. docker login [to login to docker hub from terminal]
# 2. docker tag <image_id> <dockerhub_username>/<repository_name>:<tag>
# 3. docker push <dockerhub_username>/<repository_name>:<tag>


# pull docker image from docker hub
# now our image is in docker hub anyone can pull it using below command
# docker pull <dockerhub_username>/<repository_name>:<tag>
# now after pulling the image anyone can run it using below command
# docker run -d -p <port 1>:<port 2> <dockerhub_username>/<repository_name>:<tag>
# Note: port 1 is the port on which we want to run the app on our local machine
# port 2 is the port which is exposed in dockerfile using EXPOSE keyword